// <auto-generated />
using System;
using EcoChef.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoChef.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401202132_AddPretVanzareReteta")]
    partial class AddPretVanzareReteta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoChef.Web.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretAchizitie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StocCurent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitateMasura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("EcoChef.Web.Models.IngredientReteta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantitateNecesara")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RetetaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RetetaId");

                    b.ToTable("IngredientRetete");
                });

            modelBuilder.Entity("EcoChef.Web.Models.Pierdere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantitatePierdere")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataPierdere")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("MotivPierdere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretPierdere")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Pierderi");
                });

            modelBuilder.Entity("EcoChef.Web.Models.Reteta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructiuni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretVanzare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TimpPreparare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Retete");
                });

            modelBuilder.Entity("EcoChef.Web.Models.IngredientReteta", b =>
                {
                    b.HasOne("EcoChef.Web.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoChef.Web.Models.Reteta", "Reteta")
                        .WithMany("IngredientReteta")
                        .HasForeignKey("RetetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Reteta");
                });

            modelBuilder.Entity("EcoChef.Web.Models.Pierdere", b =>
                {
                    b.HasOne("EcoChef.Web.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("EcoChef.Web.Models.Reteta", b =>
                {
                    b.Navigation("IngredientReteta");
                });
#pragma warning restore 612, 618
        }
    }
}
